"""empty message

Revision ID: 16cc74847549
Revises: 1c6ea372b7b9
Create Date: 2015-08-08 16:04:00.966027

"""

# revision identifiers, used by Alembic.
revision = '16cc74847549'
down_revision = '1c6ea372b7b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendship', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('friendship', sa.Column('id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendship', 'id')
    op.drop_column('friendship', 'confirmed')
    ### end Alembic commands ###
