"""empty message

Revision ID: 1c6ea372b7b9
Revises: 31e2bc5207a8
Create Date: 2015-08-05 19:21:38.852974

"""

# revision identifiers, used by Alembic.
revision = '1c6ea372b7b9'
down_revision = '31e2bc5207a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('entry_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'entry_date')
    ### end Alembic commands ###
