"""empty message

Revision ID: 275e561dc365
Revises: 374cb959d078
Create Date: 2015-08-28 21:39:46.655453

"""

# revision identifiers, used by Alembic.
revision = '275e561dc365'
down_revision = '374cb959d078'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendship', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendship', 'timestamp')
    ### end Alembic commands ###
