"""empty message

Revision ID: 2ab668097ec4
Revises: 1f06b6030e3e
Create Date: 2015-10-14 19:56:08.817820

"""

# revision identifiers, used by Alembic.
revision = '2ab668097ec4'
down_revision = '1f06b6030e3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_request')
    ### end Alembic commands ###
