"""empty message

Revision ID: 3182e427607e
Revises: 54e0b109626e
Create Date: 2015-09-08 20:49:06.088972

"""

# revision identifiers, used by Alembic.
revision = '3182e427607e'
down_revision = '54e0b109626e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    ### end Alembic commands ###
