"""empty message

Revision ID: 31e2bc5207a8
Revises: 3b79dff60e8c
Create Date: 2015-06-28 20:51:04.323361

"""

# revision identifiers, used by Alembic.
revision = '31e2bc5207a8'
down_revision = '3b79dff60e8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    ### end Alembic commands ###
