"""empty message

Revision ID: 4892ebc95a5
Revises: 16cc74847549
Create Date: 2015-08-10 20:14:45.770383

"""

# revision identifiers, used by Alembic.
revision = '4892ebc95a5'
down_revision = '16cc74847549'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    ### end Alembic commands ###
