"""empty message

Revision ID: 574c8d2b4a6f
Revises: 7d9b7f4c182
Create Date: 2015-12-18 07:40:14.547742

"""

# revision identifiers, used by Alembic.
revision = '574c8d2b4a6f'
down_revision = '7d9b7f4c182'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_weight')
    ### end Alembic commands ###
