"""empty message

Revision ID: f8233b437b5
Revises: 574c8d2b4a6f
Create Date: 2015-12-21 17:38:06.194561

"""

# revision identifiers, used by Alembic.
revision = 'f8233b437b5'
down_revision = '574c8d2b4a6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_setting', sa.Column('weight_day', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder_setting', 'weight_day')
    ### end Alembic commands ###
